version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/sitture/gauge-reportserver
    steps:
      - checkout
      - run:
          name: Get all dependencies
          command: go get ./...
      - run:
          name: Run Tests
          command: go test ./... -cover
      - run:
          name: Make Binaries
          command: go run build/make.go --all-platforms
  deploy:
    docker:
      - image: maven:3-jdk-8-alpine
    steps:
      - checkout

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/